const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{Atacando: 0},
	{estaMorto: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{Cronômetro: 0},
	{Nightborne: 0},
	{Teclado: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Mosaico2: 0},
	{Spawn: 0},
	{Fragmento: 0},
	{Vida: 0},
	{Inimigo: 0},
	{Portal: 0},
	{Projétil: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Foice: 0},
	{Sprite6: 0},
	{Áudio: 0},
	{Gatilho_Fase2: 0},
	{CheckPoint_Inicio: 0},
	{Âncora: 0},
	{Vida1: 0},
	{Vida2: 0},
	{Vida3: 0},
	{Sprite3: 0},
	{Vida4: 0},
	{Vida5: 0},
	{Sprite7: 0},
	{DanoPersonagem: 0},
	{VidaPlayer: 0},
	{DestinoX: 0},
	{DestinoY: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Nightborne: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Spawn: class extends self.ISpriteInstance {},
	Fragmento: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Projétil: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Foice: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Gatilho_Fase2: class extends self.ISpriteInstance {},
	CheckPoint_Inicio: class extends self.ISpriteInstance {},
	Vida1: class extends self.ISpriteInstance {},
	Vida2: class extends self.ISpriteInstance {},
	Vida3: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Vida4: class extends self.ISpriteInstance {},
	Vida5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {}
}